REMOVED don't read CHECKS from project directory

diff --git a/plugins/checks/check-deploy b/plugins/checks/check-deploy
--- a/plugins/checks/check-deploy
+++ b/plugins/checks/check-deploy
@@ -18,32 +18,25 @@ CONTAINERID="$1"; APP="$2"; PORT="$3" ; HOSTNAME="${4:-localhost}"
 
 # source in app env to get DOKKU_CHECKS_WAIT and any other necessary vars
 [[ -f "$DOKKU_ROOT/$APP/ENV" ]] && source $DOKKU_ROOT/$APP/ENV
-# echo "DOKKU_CHECKS_WAIT is $DOKKU_CHECKS_WAIT"
-FILENAME="$DOKKU_ROOT/$APP/CHECKS"
 WAIT="${DOKKU_CHECKS_WAIT:-5}"
 
 # try to copy CHECKS from container if not in APP dir & quit gracefully if it doesn't exist
 # docker cp exits with status 1 when run as non-root user when it tries to chown the file
 # after successfully copying the file. Thus, we suppress stderr.
 # ref: https://github.com/dotcloud/docker/issues/3986
-if [[ ! -f "$FILENAME" ]] ; then
-    echo "       check-deploy: $FILENAME not found. attempting to retrieve it from container ..."
-    TMPDIR=$(mktemp -d /tmp/CHECKS.XXXXX)
-    docker cp $CONTAINERID:/app/CHECKS $TMPDIR 2> /dev/null || true
-    if [[ ! -s "${TMPDIR}/CHECKS" ]] ; then
-        echo "       CHECKS file not found in container. skipping checks."
-        rm -rf $TMPDIR
-        exit 0
-    else
-        echo "       CHECKS file found in container"
-        FILENAME=${TMPDIR}/CHECKS
+TMPDIR=$(mktemp -d /tmp/CHECKS.XXXXX)
+docker cp $CONTAINERID:/app/CHECKS $TMPDIR 2> /dev/null || true
+if [[ ! -s "${TMPDIR}/CHECKS" ]] ; then
+    echo "       CHECKS file not found in container. skipping checks."
+    rm -rf $TMPDIR
+    exit 0
+else
+    FILENAME=${TMPDIR}/CHECKS
 
-        function cleanup() {
-          echo "       removing CHECKS file copied from container"
-          rm -rf $TMPDIR
-        }
-        trap cleanup EXIT
-    fi
+    function cleanup() {
+      rm -rf $TMPDIR
+    }
+    trap cleanup EXIT
 fi
 
 echo "Waiting $WAIT seconds ..."
