REMOVED don't show curl progress in logs

diff --git a/plugins/checks/check-deploy b/plugins/checks/check-deploy
--- a/plugins/checks/check-deploy
+++ b/plugins/checks/check-deploy
@@ -115,18 +115,33 @@ while read PATHNAME EXPECTED ; do
     CURL_ARGS="$CURL_OPTIONS http://$HOSTNAME:$PORT$PATHNAME"
   fi
 
-  function fail() {
-    echo -e "       \033[31m\033[1m$URL: expected to but did not find: \"$EXPECTED\"\033[0m"
+  echo -e "       \033[37m\033[1mcurl $CURL_ARGS\033[0m"
+  HTML=$(curl -# $CURL_ARGS 2>&1) || \
+    echo -e "       \033[31m\033[1m$HTML\033[0m" &&
     exit 1
-  }
-  trap fail ERR
+  if [[ "$HTML" =~ "$EXPECTED" ]] ; then
+    echo -e "       \033[32m\033[1m$URL => \"$EXPECTED\"\033[0m"
+  else
+    echo -e "       \033[31m\033[1m$URL: expected to but did not find: \"$EXPECTED\"\033[0m" && \
+    exit 1
+  fi
 
   echo -e "       \033[37m\033[1mcurl $CURL_ARGS\033[0m"
-  HTML=$(curl $CURL_ARGS)
-  [[ "$HTML" =~ $EXPECTED ]]
-  echo -e "       \033[32m\033[1m$URL => \"$EXPECTED\"\033[0m"
+  # Capture HTTP response or CURL error message
+  if OUTPUT=$(curl -# $CURL_ARGS 2>&1) ; then
+    # OUTPUT contains the HTTP response
+    if [[ "$OUTPUT" =~ $EXPECTED ]] ; then
+      echo -e "       \033[32m\033[1m$URL => \"$EXPECTED\"\033[0m"
+    else
+      echo -e "       \033[31m\033[1m$URL: expected to but did not find: \"$EXPECTED\"\033[0m" && \
+      exit 1
+    fi
+  else
+    # Failed to connect/no response, OUTPUT contains error message
+    echo -e "       \033[31m\033[1m$OUTPUT\033[0m" &&
+    exit $?
+  fi
 
-  trap - ERR
 done
 
 
